### ISSUE TITLE
Notepad is blank when opening files

### ISSUE THREAD

**Issue by PiSaucer** [1j01/98#60]
I forked this project and use a subdomain. Whenever I try to use the notepad app it will as open a blank file. I included a screenshot of `CREDITS.txt`. I noticed that it gave out this error in the console. Any ideas to fix this?

<img width="525" alt="Screen Shot 2022-02-27 at 7 24 47 PM" src="https://user-images.githubusercontent.com/33438654/155909682-9855a9db-e1ee-4024-b594-3a4098c023f6.png">

```
Uncaught Error: Invalid buffer: Buffer is 582 long, yet Stats object specifies that file is 277 long. preload_file.ts
    at OverlayFile.PreloadFile [as constructor] (preload_file.ts:57:13)
    at new OverlayFile (OverlayFS.ts:35:10)
    at OverlayFS.ts:421:27
    at XmlHttpRequest.ts:373:18
    at NoSyncFile.close (preload_file.ts:404:5)
    at cb (XmlHttpRequest.ts:369:13)
    at XmlHttpRequest.ts:379:9
    at XmlHttpRequest.ts:290:20
    at XMLHttpRequest.req.onreadystatechange (xhr.ts:44:20)
```

**Comment by PiSaucer** [comment]
I notice that JSPaint also doesn't work when it's hosted not locally:

<img width="528" alt="Screen Shot 2022-02-28 at 6 44 01 PM" src="https://user-images.githubusercontent.com/33438654/156083091-09fab342-b9f7-4608-ab5e-949a6cd6495f.png">

```
Uncaught Error: Invalid buffer: Buffer is 56017 long, yet Stats object specifies that file is 52339 long.
    at OverlayFile.PreloadFile [as constructor] (preload_file.ts:57:13)
    at new OverlayFile (OverlayFS.ts:35:10)
    at OverlayFS.ts:421:27
    at XmlHttpRequest.ts:373:18
    at NoSyncFile.close (preload_file.ts:404:5)
    at cb (XmlHttpRequest.ts:369:13)
    at XmlHttpRequest.ts:379:9
    at XmlHttpRequest.ts:290:20
    at XMLHttpRequest.req.onreadystatechange (xhr.ts:44:20)
    ```

**Comment by cherrim98** [comment]
I seem to have this issue too. Not sure why that is the case. Paint works fine for me, though.
